'use client';

import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Download } from 'lucide-react';
import { motion } from 'framer-motion';
import { toast, Toaster } from 'sonner';

interface ExportPdfButtonProps {
  reportId: string;
}

export const ExportPdfButton: React.FC<ExportPdfButtonProps> = ({ reportId }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleExport = async () => {
    const element = document.getElementById(reportId);
    if (!element) return;

    setIsGenerating(true);

    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        backgroundColor: '#09090b',
        logging: false,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

      pdf.addImage(imgData, 'PNG', 0, 10, pdfWidth, pdfHeight);
      pdf.setFontSize(10);
      pdf.text('Generated by VeloCV AI', pdfWidth / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' });
      
      pdf.save('velocv-analysis-report.pdf');
      toast.success('PDF report downloaded successfully');
    } catch (error: any) {
      console.error('PDF generation detailed error:', error);
      toast.error(`Failed to generate PDF: ${error.message || 'Unknown error'}`);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <Toaster position="bottom-right" theme="dark" />
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handleExport}
        disabled={isGenerating}
        className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-blue-600 to-violet-600 hover:from-blue-500 hover:to-violet-500 text-white rounded-2xl font-semibold shadow-lg hover:shadow-[0_0_20px_rgba(59,130,246,0.3)] transition-all duration-300 disabled:opacity-50"
      >
        <Download className="w-4 h-4" />
        {isGenerating ? 'Generating PDF...' : 'Download PDF Report'}
      </motion.button>
    </>
  );
};
