import React from 'react';

// This is an isolated, non-tailwind version for the PDF generator.
export const PDFTemplate = ({ result }: { result: any }) => (
  <div 
    id="ats-report-pdf-target" 
    style={{ 
      backgroundColor: '#0f172a', 
      color: '#ffffff',
      padding: '40px',
      fontFamily: 'sans-serif',
      width: '600px'
    }}
  >
    <h1 style={{ textAlign: 'center', marginBottom: '20px' }}>VeloCV Analysis Report</h1>
    
    <div style={{ textAlign: 'center', marginBottom: '30px' }}>
      <div style={{ fontSize: '48px', fontWeight: 'bold' }}>{result.atsScore}%</div>
      <div style={{ color: '#94a3b8' }}>ATS Match Score</div>
    </div>

    <div style={{ marginBottom: '20px' }}>
      <h3 style={{ color: '#94a3b8' }}>Skills</h3>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
        {result.skills?.map((s: string, i: number) => (
          <span key={i} style={{ backgroundColor: '#1e3a8a', padding: '4px 8px', borderRadius: '4px' }}>{s}</span>
        ))}
      </div>
    </div>

    <div style={{ display: 'flex', gap: '20px' }}>
      <div style={{ flex: 1 }}>
        <h3 style={{ color: '#34d399' }}>Fortalezas</h3>
        <ul style={{ color: '#cbd5e1' }}>
          {result.strengths?.map((s: string, i: number) => <li key={i}>{s}</li>)}
        </ul>
      </div>
      <div style={{ flex: 1 }}>
        <h3 style={{ color: '#fb7185' }}>Debilidades</h3>
        <ul style={{ color: '#cbd5e1' }}>
          {result.weaknesses?.map((w: string, i: number) => <li key={i}>{w}</li>)}
        </ul>
      </div>
    </div>
    
    <div style={{ marginTop: '40px', textAlign: 'center', color: '#64748b' }}>
      Generated by VeloCV AI
    </div>
  </div>
);
